version: "3.7"

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=testing
    ports:
      - 5432:5432
